# Generated by Django 4.2.7 on 2025-07-08 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_job_applications", models.BooleanField(default=True)),
                ("email_application_status", models.BooleanField(default=True)),
                ("email_new_job_matches", models.BooleanField(default=True)),
                ("email_system_updates", models.BooleanField(default=True)),
                ("web_job_applications", models.BooleanField(default=True)),
                ("web_application_status", models.BooleanField(default=True)),
                ("web_new_job_matches", models.BooleanField(default=True)),
                ("web_system_updates", models.BooleanField(default=True)),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                            ("never", "Never"),
                        ],
                        default="instant",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("job_application", "Job Application"),
                            ("application_status", "Application Status Update"),
                            ("new_job_match", "New Job Match"),
                            ("job_posted", "Job Posted"),
                            ("profile_incomplete", "Profile Incomplete"),
                            ("application_deadline", "Application Deadline"),
                            ("system", "System Notification"),
                            ("welcome", "Welcome Message"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("action_url", models.URLField(blank=True, null=True)),
                (
                    "action_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="user_notifi_recipie_6e1118_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="user_notifi_recipie_1ce727_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="user_notifi_notific_501917_idx",
                    ),
                ],
            },
        ),
    ]
