# Generated by Django 4.2.7 on 2025-07-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_notifications", "0001_initial"),
    ]

    operations = []
